#
# Docker Nginx Component
# creator: David
#
- name: ensure nginx directory exists
  file: path=/home/ubuntu/nginx/stable-alpine/conf state=directory
  become: no
- name: ensure rsync is installed
  apt: name=rsync
- name: push the local nginx configuration to the remote machine
  synchronize: |
    src=../playbooks/conf/nginx/
    dest=/home/ubuntu/nginx/stable-alpine/conf
    mode=push
  become: no
- name: ensure nginx docker instance is configured and running
  docker_container:
    name: nginx
    image: nginx:stable-alpine
    volumes:
      - /home/ubuntu/nginx/stable-alpine/conf/auth:/etc/nginx/auth
      -  /home/ubuntu/nginx/stable-alpine/conf/conf.d:/etc/nginx/conf.d
      -  /home/ubuntu/nginx/stable-alpine/conf/sites-available:/etc/nginx/sites-available
      -  /home/ubuntu/nginx/stable-alpine/conf/sites-enabled:/etc/nginx/sites-enabled
      -  /home/ubuntu/nginx/stable-alpine/conf/ssl:/etc/nginx/ssl
      -  /home/ubuntu/nginx/stable-alpine/conf/nginx.conf:/etc/nginx/nginx.conf
    state: started
    restart: yes
    network_mode: touchframe
    ports:
      - 80:80
      - 443:443
